name: main publish

on:
  push:
    branches:
      - main
    paths:
      - src/package/**
      - .github/**

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install packages
        run: yarn
        working-directory: src/package
      - name: update version
        run: yarn update-version
        working-directory: src/package
      - name: publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        working-directory: src/package