name: material dev publish

on:
  push:
    branches:
      - develop
    paths:
      - src/colop-material/**
      - .github/**

env:
  ENVIRONMENT:  ${{ vars.ENVIRONMENT }}

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install packages
        run: yarn install --frozen-lockfile
        working-directory: src/colop-material
      - name: build
        run: yarn build
        working-directory: src/colop-material
      - name: update version
        run: yarn update-version
        working-directory: src/colop-material
      - name: publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        working-directory: src/colop-material