name: material publish check

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - src/colop-material/**
      - .github/**

jobs:

  build-material:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install packages
        run: yarn install --frozen-lockfile
        working-directory: src/colop-material
      - name: build
        run: yarn build
        working-directory: src/colop-material